### ISSUE TITLE
Resolve `grpcio_sys` compile under Debian Trixie

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/autopush-rs#1167]
Under Ubuntu 25.10 (which runs Debian “Trixie” / Linux Kernel 6.17.0 ) `grpcio_sys` fails to compile due to a no longer valid reference:

> ```powershell
> /home/jrconlin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/grpcio-sys-0.13.0+1.56.2-patched/grpc/third_party/abseil-cpp/absl/container/internal/container_memory.h:66:27: error: 'uintptr_t' does not name a type [-Wtemplate-body]
>      66 |   assert(reinterpret_cast<uintptr_t>(p) % Alignment == 0 &&
>         |                           ^~~~~~~~~
>   /home/jrconlin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/grpcio-sys-0.13.0+1.56.2-patched/grpc/third_party/abseil-cpp/absl/container/internal/container_memory.h:31:1: note: 'uintptr_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
>      30 | #include "absl/utility/utility.h"
>     +++ |+#include <cstdint>
>      31 |
>   gmake[3]: *** [third_party/abseil-cpp/absl/flags/CMakeFiles/flags_reflection.dir/build.make:79: third_party/abseil-cpp/absl/flags/CMakeFiles/flags_reflection.dir/reflection.cc.o] Error 1
> ```

It is possible to continue to build using a Docker container `rust:1.91-bookworm`, however, this is not sustainable over a long term.

We need to decide if we want to:

1. convert to a different backend that does not use grpcio_sys but supports bigtable (see parent ticket)
2. Fork the existing grpcio-sys v0.13.0+1.56.2-patched to include the required fixes.
3. some other approach

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/PUSH-582)
